# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 19:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='DEFAULT', max_length=200)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('companyName', models.CharField(max_length=200)),
                ('companyPhone', models.CharField(max_length=200)),
                ('companyLocation', models.CharField(max_length=200)),
                ('companyCountry', models.CharField(max_length=200)),
                ('sector', models.CharField(max_length=200)),
                ('industry', models.CharField(max_length=200)),
                ('currentProjects', models.TextField()),
            ],
        ),
    ]
