# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LokahiApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='title',
        ),
        migrations.AlterField(
            model_name='report',
            name='companyName',
            field=models.CharField(default='DEFAULT', max_length=200),
        ),
    ]
