# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LokahiApp', '0002_auto_20170403_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='upload',
            field=models.FileField(default='', upload_to='/media/'),
        ),
        migrations.AlterField(
            model_name='report',
            name='companyCountry',
            field=models.CharField(default='DEFAULT', max_length=200),
        ),
        migrations.AlterField(
            model_name='report',
            name='companyLocation',
            field=models.CharField(default='DEFAULT', max_length=200),
        ),
        migrations.AlterField(
            model_name='report',
            name='companyPhone',
            field=models.CharField(default='DEFAULT', max_length=200),
        ),
        migrations.AlterField(
            model_name='report',
            name='currentProjects',
            field=models.TextField(default='DEFAULT'),
        ),
        migrations.AlterField(
            model_name='report',
            name='industry',
            field=models.CharField(default='DEFAULT', max_length=200),
        ),
        migrations.AlterField(
            model_name='report',
            name='sector',
            field=models.CharField(default='DEFAULT', max_length=200),
        ),
    ]
