# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LokahiApp', '0003_auto_20170410_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='upload',
            field=models.FileField(default=True, upload_to='media'),
        ),
    ]
