# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-12 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LokahiApp', '0004_auto_20170411_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='encrypted',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=2),
        ),
    ]
